###
GET http://localhost:8080/redis/number

### READ ONE
// @no-log
< {%
    request.variables.set("key", (Math.random() * 10).toFixed(0))
%}
GET http://localhost:8080/redis/sample?key={{key}}

### CREATE ONE
// @no-log
< {%
    request.variables.set("key", (Math.random() * 10).toFixed(0))
%}
POST http://localhost:8080/redis/sample
Content-Type: application/json
Accept: application/json

{
  "key": "{{key}}",
  "value": "{{key}}"
}

### UPDATE ONE
// @no-log
< {%
    const key = (Math.random() * 10).toFixed(0)
    request.variables.set("key", key)
    request.variables.set("value", (parseInt(key) + 1).toString())
%}
PUT http://localhost:8080/redis/sample
Content-Type: application/json
Accept: application/json

{
  "key": "{{key}}",
  "value": "{{value}}"
}

### DELETE ONE
// @no-log
< {%
    request.variables.set("key", (Math.random() * 10).toFixed(0))
%}
DELETE http://localhost:8080/redis/sample?key={{key}}

### DELETE ALL
// @no-log

